spring:
  data:
    mongodb:
      uri: mongodb+srv://santoshkumawatdev:hpy38NIXefq2C2nf@cluster0.bs3ad.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8080

weather:
  api:
    key: "{YOUR_API_KEY}"

debug: false